### PR TITLE
React peerDependencies with v18

### PR DESCRIPTION
**Pull request by lukomwro**
I'm using this lib for a while with a React `v18.2.0` and everything works fine. So we can basically add React v18 in peerDeps.

Cheers 👋

### CODE REVIEW

**Comment by reintroducing** [comment]
@everweij is it possible to get this merged? Would also close the bug that is open with this issue as well. Thank you.

**Comment by ssijak** [comment]
@everweij can you please merge this PR? thanks!!

**Comment by Skaidon** [comment]
@everweij is there any way this PR (or at least a similar fix) can be released? Thanks!

**Comment by vymao** [comment]
Bump

**Review by arbughiu — APPROVED** [review]

**Comment by everweij** [comment]
Hey guys, I'm sorry this took so long!
Thanks for the PR. I will release a new version shortly after merging this PR.

**Pull request merged**
